name:         John Novak Blog
description:  Personal blog of John Novak
url:          http://johnnovak.net/

timezone:     Australia/Brisbane
encoding:     utf-8

permalink:    :year/:month/:day/:title/

markdown:     kramdown
pygments:     false

exclude:      [*.scss, *.css.map]
