name:         Personal blog of John Novak
description:  Personal blog of John Novak

timezone:     Australia/Brisbane
encoding:     utf-8

permalink:    :year/:month/:day/:title/

markdown:     kramdown
highlighter:  pygments

sass:
    sass_dir: _sass

gems:
    - jekyll-redirect-from

# User variables

url:          https://blog.johnnovak.net
rootdir:      ""

