name:         John Novak's blog
description:  Personal blog of John Novak
url:          http://johnnovak.net

baseurl:      /blog

permalink:    :year/:month/:day/:title/
encoding:     UTF8-MAC

pygments:     false
